import React from 'react';
import LegalLayout, { Section } from './LegalLayout';
import { CONTACT_EMAIL, MANISH_LABS_URL } from '../config/links';

const TermsPage = () => {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="June 5, 2026"
      intro="These terms govern your use of Trace, an AI-assisted debugging platform operated by Manish Labs. By creating an account or using Trace, you agree to them. Please read them carefully."
    >
      <Section title="1. The service">
        <p>
          Trace helps developers understand and resolve software errors using AI-generated diagnostics,
          a Socratic learning approach, growth analytics, and a community knowledge library. Trace is
          provided as-is and is continually evolving — features may change, be added, or be removed.
        </p>
      </Section>

      <Section title="2. Your account">
        <p>
          You are responsible for the activity under your account and for keeping your credentials
          secure. You must provide accurate information and be old enough to form a binding contract in
          your jurisdiction. Notify us promptly of any unauthorized use.
        </p>
      </Section>

      <Section title="3. Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>Submit content that is unlawful, malicious, or infringes others' rights.</li>
          <li>Attempt to disrupt, overload, reverse-engineer, or gain unauthorized access to the service.</li>
          <li>Use Trace to generate or distribute malware, or to harass or harm others.</li>
          <li>Abuse free-tier limits through automated or large-scale circumvention.</li>
        </ul>
      </Section>

      <Section title="4. AI-generated content">
        <p>
          Trace's diagnostics, explanations, and suggestions are generated by AI models and may be
          incomplete or incorrect. They are guidance, not professional advice. Always review and test
          AI suggestions before applying them to production systems. You are responsible for any code
          you ship.
        </p>
      </Section>

      <Section title="5. Your content & the Library">
        <p>
          You retain ownership of the error logs, notes, and conversations you submit. When you choose
          to publish a resolved fix to the shared Library, you grant Manish Labs a non-exclusive,
          worldwide licence to host and display that article so other developers can learn from it. You
          can choose to publish under your name or anonymously, and you should not include secrets,
          credentials, or personal data in published content.
        </p>
      </Section>

      <Section title="6. Service limits">
        <p>
          Trace offers a free tier with daily usage allowances that are managed to keep the service
          available and affordable for everyone. We may adjust these limits over time.
        </p>
      </Section>

      <Section title="7. Third-party services">
        <p>
          Trace uses third-party AI providers (such as Google's Gemini models) to process requests. Your
          use of Trace is also subject to those providers' applicable terms. See our{' '}
          <a href="/privacy">Privacy Policy</a> for how data is handled.
        </p>
      </Section>

      <Section title="8. Disclaimers & liability">
        <p>
          Trace is provided "as is" without warranties of any kind. To the maximum extent permitted by
          law, Manish Labs is not liable for any indirect, incidental, or consequential damages, or for
          any loss arising from reliance on AI-generated output or from interruptions to the service.
        </p>
      </Section>

      <Section title="9. Termination">
        <p>
          You may stop using Trace and delete your data at any time. We may suspend or terminate access
          that violates these terms or harms the service or other users.
        </p>
      </Section>

      <Section title="10. Changes to these terms">
        <p>
          We may update these terms as Trace evolves. Material changes will be reflected by updating the
          date above. Continued use after changes means you accept the revised terms.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these terms? Reach out at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>{' '}
          or visit <a href={MANISH_LABS_URL} target="_blank" rel="noreferrer">Manish Labs</a>.
        </p>
      </Section>
    </LegalLayout>
  );
};

export default TermsPage;
